import React from 'react'

import '@/styles/globals.css'
import '@bamotf/react/components.css'

import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-evenly">
          {children}
        </main>
      </body>
    </html>
  )
}
