import Link from 'next/link'

import './globals.css'
import '@bam-otf/react/styles.css'

import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-evenly p-24">
          <div className="items-center justify-between font-mono text-sm lg:flex">
            <Link
              href="/"
              className="flex w-auto justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30"
            >
              <b className="font-bold mr-4">bam-otf</b> donation&nbsp;demo
            </Link>
          </div>
          {children}
        </main>
      </body>
    </html>
  )
}
